name: Build and Deploy Python App to ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # ✅ Allow manual "Run Workflow" from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533267394172.dkr.ecr.us-east-1.amazonaws.com

    - name: Build, Tag, and Push Docker image
      run: |
        docker build -t python-ecs-app:${{ github.run_number }} .
        docker tag python-ecs-app:${{ github.run_number }} 533267394172.dkr.ecr.us-east-1.amazonaws.com/python-ecs-app:${{ github.run_number }}
        docker push 533267394172.dkr.ecr.us-east-1.amazonaws.com/python-ecs-app:${{ github.run_number }}

    - name: Update ECS Service
      run: |
        aws ecs update-service --cluster my-ecs-cluster --service python-ece-app-service-malrytj4 --force-new-deployment
